#!/usr/bin/env bash
set -euo pipefail

# ARC Attestation Spike — run on a rented GPU instance
#
# Platform requirements (validated live 2026-06-10, nvattest 1.2.2):
#   - Blackwell (B200/GB200): corelib evidence source works with CC OFF.
#     Any stock rental box works. Pass --gpu-architecture blackwell (automatic).
#   - Hopper (H100/H200): evidence collection requires CC or PPCIe mode.
#     A stock rental VM does NOT qualify (CPU TEE absent -> CC UNAVAILABLE).
#     You need a confidential VM (e.g. Azure NCC H100 v5) or a host with CC
#     enabled. This script fails fast with an explanation otherwise.
#   - Ubuntu 22.04 / 24.04, outbound HTTPS to *.attestation.nvidia.com.
#
# Nonce requirements (validated live): nvattest 1.2.2 rejects nonces shorter
# than 32 bytes. Use 64-hex-char nonces.
#
# Nonce custody: for receipts a third party should rely on, the challenge
# nonce must be generated by the RELYING PARTY (lender) and recorded before
# this script runs, not invented on the provider's box. Pass it via:
#   ARC_NONCES="<nonce1> <nonce2> ..." ./capture_gpu_attestation.sh out_dir
# If unset, the script generates nonces locally and marks them
# operator-generated in nonce_custody.txt (weaker; fine for the spike).

out_dir="${1:-attestation_spike}"
runs="${ARC_RUNS:-3}"
mkdir -p "$out_dir"

echo "=== Step 1: Record CC mode, GPU info, tool version, environment ==="
nvidia-smi conf-compute -f 2>&1 | tee "$out_dir/cc_status.txt" || true
for opt in -gc -gg -e -d; do
    nvidia-smi conf-compute "$opt" 2>&1 || true
done | tee "$out_dir/cc_capability_queries.txt"
nvidia-smi --query-gpu=index,name,serial,uuid,driver_version,vbios_version --format=csv,noheader | tee "$out_dir/gpu_info.txt"
{
    echo "captured_at_utc: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "uname: $(uname -a)"
    echo "uptime_seconds: $(awk '{print $1}' /proc/uptime)"
    command -v lsb_release >/dev/null && echo "os: $(lsb_release -ds)"
    echo "nvidia_driver: $(nvidia-smi --query-gpu=driver_version --format=csv,noheader | head -1)"
} | tee "$out_dir/environment_notes.txt"

gpu_name=$(nvidia-smi --query-gpu=name --format=csv,noheader | head -1)
cc_status=$(nvidia-smi conf-compute -f 2>/dev/null | grep -oE "ON|OFF" | head -1 || echo "UNKNOWN")
case "$gpu_name" in
    *B100*|*B200*|*B300*|*GB1*|*GB2*|*GB3*) gpu_arch="blackwell" ;;
    *H100*|*H200*|*GH1*|*GH2*)              gpu_arch="hopper" ;;
    *)                                       gpu_arch="unknown" ;;
esac
echo "gpu_name: $gpu_name / arch: $gpu_arch / cc: $cc_status"

# Pick the evidence source the platform can actually serve, or fail fast.
evidence_source="${ARC_EVIDENCE_SOURCE:-}"
if [ -z "$evidence_source" ]; then
    if [ "$cc_status" = "ON" ]; then
        evidence_source="nvml"
    elif [ "$gpu_arch" = "blackwell" ]; then
        evidence_source="corelib"
    else
        echo "FATAL: CC is $cc_status and arch is $gpu_arch."
        echo "  - corelib (CC-off path) supports blackwell only in nvattest 1.2.x"
        echo "  - nvml requires the GPU to be in CC or PPCIe mode"
        echo "  A stock rented Hopper VM cannot produce device attestation."
        echo "  Use a Blackwell box, or a CC-enabled Hopper platform (confidential VM)."
        exit 2
    fi
fi
echo "evidence_source: $evidence_source" | tee -a "$out_dir/environment_notes.txt"
arch_flag=""
[ "$evidence_source" = "corelib" ] && arch_flag="--gpu-architecture blackwell"

# corelib talks SPDM over PCIe DOE registers in EXTENDED config space.
# Containers (RunPod et al.) hide the GPU PCI device and cap config reads at
# the legacy 64 bytes (validated live 2026-06-10) — fail fast there.
if [ "$evidence_source" = "corelib" ]; then
    pci_addr=$(nvidia-smi --query-gpu=pci.bus_id --format=csv,noheader | head -1 | sed 's/^0000//' | tr '[:upper:]' '[:lower:]')
    cfg="/sys/bus/pci/devices/0000:${pci_addr#0000:}/config"
    # must read as root: the kernel caps non-root config reads at 64 bytes
    cfg_bytes=$(sudo cat "$cfg" 2>/dev/null | wc -c || echo 0)
    if [ "$cfg_bytes" -lt 4096 ]; then
        echo "FATAL: GPU PCIe extended config space not accessible (got ${cfg_bytes} bytes at $cfg)."
        echo "  corelib needs DOE access to the GPU's PCI function. Containers do not expose it."
        echo "  Use a real VM with GPU passthrough or bare metal."
        exit 2
    fi
fi
echo ""

echo "=== Step 2: Install attestation SDK ==="
if ! command -v nvattest &>/dev/null; then
    echo "Installing build dependencies..."
    sudo apt-get update && sudo apt-get install -y \
        cmake git pkg-config clang zlib1g-dev \
        libcurl4-openssl-dev libssl-dev libxml2-dev \
        libxml2 libxmlsec1-dev libxmlsec1-openssl

    if ! command -v rustc &>/dev/null; then
        echo "Installing Rust..."
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source "$HOME/.cargo/env"
    fi

    echo "Building nvattest..."
    git clone https://github.com/NVIDIA/attestation-sdk.git /tmp/attestation-sdk
    cd /tmp/attestation-sdk/nv-attestation-cli
    cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    cmake --build build
    sudo cmake --install build
    sudo ldconfig
    cd -
else
    echo "nvattest already installed"
fi
nvattest version 2>&1 | tee "$out_dir/nvattest_version.txt"
nvattest attest --help > "$out_dir/nvattest_attest_help.txt" 2>&1 || true

# corelib is a separate runtime library, packaged as libcorelib1 in
# NVIDIA-enabled apt repos (validated live: dlopen of libcorelib.so.1).
if [ "$evidence_source" = "corelib" ] && ! ldconfig -p | grep -q "libcorelib.so.1"; then
    echo "Installing libcorelib1..."
    sudo apt-get install -y libcorelib1 && sudo ldconfig || {
        echo "FATAL: libcorelib1 not installable — image lacks the NVIDIA apt repo carrying it."
        exit 2
    }
fi
echo ""

echo "=== Step 3: Check RIM availability for this GPU family ==="
vbios_version=$(nvidia-smi --query-gpu=vbios_version --format=csv,noheader | head -1 | tr -d ' ')
echo "VBIOS: $vbios_version"
curl -s https://rim.attestation.nvidia.com/v1/rim/ids | python3 -c "
import json, sys
name = '''$gpu_name'''
tokens = [t for t in name.replace('NVIDIA', '').split() if any(ch.isdigit() for ch in t)]
token = tokens[0] if tokens else 'H100'
data = json.load(sys.stdin)
ids = data.get('ids', [])
hits = [x for x in ids if token in x or ('G' + token) in x]
print(f'{token} RIM entries found: {len(hits)}')
for rim in hits[:10]:
    print(f'  {rim}')
" 2>&1 | tee "$out_dir/rim_check.txt"
echo ""

echo "=== Step 4: Nonce custody ==="
if [ -n "${ARC_NONCES:-}" ]; then
    read -r -a nonces <<< "$ARC_NONCES"
    echo "relying-party-supplied nonces (${#nonces[@]})" | tee "$out_dir/nonce_custody.txt"
else
    nonces=()
    for i in $(seq 1 "$runs"); do
        nonces+=("$(python3 -c "import secrets; print(secrets.token_hex(32))")")
    done
    echo "operator-generated nonces (weaker custody; spike only)" | tee "$out_dir/nonce_custody.txt"
fi
for nonce in "${nonces[@]}"; do
    if [ "${#nonce}" -lt 64 ]; then
        echo "FATAL: nonce '$nonce' is ${#nonce} hex chars; nvattest 1.2.x requires >= 64 (32 bytes)."
        echo "Regenerate with: python3 -c \"import secrets; print(secrets.token_hex(32))\""
        exit 2
    fi
done
echo ""

echo "=== Step 5: Repeat nonce-bound attestation runs (${#nonces[@]}) ==="
run_idx=0
for nonce in "${nonces[@]}"; do
    run_idx=$((run_idx + 1))
    run_dir="$out_dir/run_$run_idx"
    mkdir -p "$run_dir"
    echo "$nonce" > "$run_dir/challenge_nonce.txt"
    date -u +%Y-%m-%dT%H:%M:%SZ > "$run_dir/collected_at.txt"

    if [ "$evidence_source" = "corelib" ]; then
        # corelib only works with the collect-evidence subcommand (validated
        # live on nvattest 1.2.2); attest then appraises the evidence file.
        # corelib reads PCIe DOE registers -> needs root
        collect_cmd="sudo nvattest --format json collect-evidence --device gpu --gpu-evidence-source corelib $arch_flag --nonce $nonce"
        cmd="nvattest --format json attest --device gpu --verifier remote --gpu-evidence-source file --gpu-evidence-file $run_dir/gpu_evidence.json --nonce $nonce"
        printf '%s\n%s\n' "$collect_cmd" "$cmd" > "$run_dir/command.txt"
        echo "--- run $run_idx (collect): $collect_cmd"
        $collect_cmd > "$run_dir/gpu_evidence.json" 2> "$run_dir/collect_evidence_log.txt" || \
            echo "run $run_idx collect exited nonzero; see collect_evidence_log.txt"
        shasum -a 256 "$run_dir/gpu_evidence.json" | tee "$run_dir/collected_evidence_sha256.txt"
    else
        cmd="nvattest --format json attest --device gpu --verifier remote --gpu-evidence-source $evidence_source --nonce $nonce"
        echo "$cmd" > "$run_dir/command.txt"
    fi
    echo "--- run $run_idx: $cmd"
    $cmd > "$run_dir/attest_response.json" 2> "$run_dir/remote_attest_log.txt" || \
        echo "run $run_idx exited nonzero; see remote_attest_log.txt"
    shasum -a 256 "$run_dir/attest_response.json" | tee "$run_dir/raw_evidence_sha256.txt"

    # Split the response envelope: claims -> importer input,
    # detached_eat -> raw signed token of record (for --raw-token).
    python3 - "$run_dir" <<'PYEOF' || echo "run $run_idx: extraction failed (see attest_response.json)"
import json, sys
from pathlib import Path
run_dir = Path(sys.argv[1])
resp = json.loads((run_dir / "attest_response.json").read_text())

if isinstance(resp, dict) and "result_code" in resp:
    print(f"  result_code={resp.get('result_code')} result_message={resp.get('result_message')!r}")
    claims = resp.get("claims")
    detached = resp.get("detached_eat")
else:
    claims, detached = resp, None

(run_dir / "real_attestation_claims.json").write_text(json.dumps(claims, indent=2) + "\n")
if detached not in (None, {}, [], ""):
    if isinstance(detached, str):
        (run_dir / "detached_eat.txt").write_text(detached + "\n")
    else:
        (run_dir / "detached_eat.json").write_text(json.dumps(detached, indent=2) + "\n")
    print("  detached EAT saved (raw token of record)")
else:
    print("  WARNING: no detached_eat in response; raw token unavailable")

def collect(obj, depth=0):
    if depth > 8:
        return
    if isinstance(obj, dict):
        if "ueid" in obj:
            yield obj
        for v in obj.values():
            yield from collect(v, depth + 1)
    elif isinstance(obj, list):
        for item in obj:
            yield from collect(item, depth + 1)

rows = []
for c in collect(claims):
    cert = c.get("x-nvidia-gpu-attestation-report-cert-chain", {})
    if not isinstance(cert, dict):
        cert = {}
    rows.append({
        "ueid": c.get("ueid"),
        "eat_nonce": c.get("eat_nonce"),
        "hwmodel": c.get("hwmodel"),
        "measres": c.get("measres"),
        "overall": c.get("x-nvidia-overall-att-result"),
        "driver": c.get("x-nvidia-gpu-driver-version"),
        "cert_status": cert.get("x-nvidia-cert-status"),
        "ocsp_status": cert.get("x-nvidia-cert-ocsp-status"),
    })
(run_dir / "extracted_fields.json").write_text(json.dumps(rows, indent=2))
(run_dir / "ueids.txt").write_text("\n".join(str(r["ueid"]) for r in rows) + "\n")
challenge = (run_dir / "challenge_nonce.txt").read_text().strip()
if not rows:
    print("  WARNING: no per-GPU claim dicts with 'ueid' found — inspect attest_response.json shape")
for r in rows:
    eat = str(r.get("eat_nonce") or "")
    exact = eat.lower() == challenge.lower()
    padded = (not exact) and eat.lower().startswith(challenge.lower()) and set(eat[len(challenge):]) == {"0"}
    print(f"  ueid={r['ueid']} eat_nonce_exact={exact} eat_nonce_zeropadded={padded} measres={r['measres']} overall={r['overall']}")
PYEOF
done
echo ""

echo "=== Step 6: UEID stability across runs (same boot) ==="
python3 - "$out_dir" <<'PYEOF' || echo "stability check failed (earlier runs may have failed)"
import sys
from pathlib import Path
out_dir = Path(sys.argv[1])
sets = {}
for run_dir in sorted(out_dir.glob("run_*")):
    f = run_dir / "ueids.txt"
    if not f.is_file():
        continue
    ueids = f.read_text().split()
    if not ueids:
        print(f"{run_dir.name}: no UEIDs captured")
        continue
    sets[run_dir.name] = set(ueids)
    print(f"{run_dir.name}: {sorted(ueids)}")
values = list(sets.values())
if not values:
    # An empty comparison must not read as stability evidence.
    (out_dir / "ueid_stability.txt").write_text("NO-DATA\n")
    raise SystemExit("no ueids captured in any run — stability is NO-DATA, not STABLE")
stable = all(v == values[0] for v in values)
verdict = "STABLE" if stable else "UNSTABLE"
print(f"UEID stability across {len(values)} same-boot runs: {verdict}")
(out_dir / "ueid_stability.txt").write_text(verdict + "\n")
PYEOF
echo ""

echo "=== Step 7: Emit identity bridge template + import command ==="
python3 - "$out_dir" <<'PYEOF' || echo "template emit failed (run_1 may have failed)"
import json, sys
from pathlib import Path
out_dir = Path(sys.argv[1])
run1 = out_dir / "run_1"
ueids = run1.joinpath("ueids.txt").read_text().split()
bridge = {
    "schedule_id": "FILL-IN-SCHEDULE-ID",
    "mapping_source": "FILL-IN: provider asset register export / onboarding doc / ticket",
    "mapping_time": "FILL-IN: ISO 8601 UTC when the mapping was established",
    "mapper": "FILL-IN: person or service that asserted the mapping",
    "mappings": [
        {"contract_gpu_id": f"FILL-IN-CONTRACT-GPU-ID-{i+1}", "provider_asset_id": "FILL-IN", "ueid": u}
        for i, u in enumerate(ueids)
    ],
}
(out_dir / "identity_bridge.template.json").write_text(json.dumps(bridge, indent=2) + "\n")
nonce = run1.joinpath("challenge_nonce.txt").read_text().strip()
collected = run1.joinpath("collected_at.txt").read_text().strip()
command = run1.joinpath("command.txt").read_text().strip()
tool_version = (out_dir / "nvattest_version.txt").read_text().strip().splitlines()[0]
gpu_name = (out_dir / "gpu_info.txt").read_text().split(",")[1].strip()
tokens = [t for t in gpu_name.replace("NVIDIA", "").split() if any(ch.isdigit() for ch in t)]
gpu_class = tokens[0] if tokens else "FILL-IN"
raw_token = "run_1/detached_eat.txt" if (run1 / "detached_eat.txt").is_file() else (
    "run_1/detached_eat.json" if (run1 / "detached_eat.json").is_file() else None)
raw_token_line = f"  --raw-token {raw_token} \\\n" if raw_token else ""
import_cmd = (
    "./import_nvattest run_1/real_attestation_claims.json \\\n"
    f"  --nonce {nonce} \\\n"
    + raw_token_line +
    "  --identity-bridge identity_bridge.template.json \\\n"
    "  --contract-id FILL-IN --window-start FILL-IN --window-end FILL-IN \\\n"
    "  --declared-gpu-id FILL-IN \\\n"
    f"  --expected-gpu-class {gpu_class} --operator FILL-IN \\\n"
    f"  --tool-version {tool_version!r} \\\n"
    f"  --command {command!r} \\\n"
    f"  --collected-at {collected} --out evidence/"
)
(out_dir / "import_command.txt").write_text(import_cmd + "\n")
print(import_cmd)
PYEOF
echo ""

echo "=== Spike complete ==="
echo "Output directory: $out_dir/"
ls -la "$out_dir/"
echo ""
echo "Next steps:"
echo "  1. Review run_*/extracted_fields.json — fields non-null, eat_nonce_exact true"
echo "  2. Check ueid_stability.txt — confirm UEIDs are stable same-boot"
echo "  3. Confirm whether the EAT nonce echo is exact (expected with 64-hex nonces)"
echo "     or zero-padded; gpu_pass_utils.nonce_bound encodes the rule"
echo "  4. run_*/detached_eat.* is the raw signed token — import with --raw-token"
echo "  5. Optional: reboot, re-run, compare ueids.txt for cross-boot stability"
echo "  6. Fill in identity_bridge.template.json from the asset register (NOT from this box)"
echo "  7. Copy run dirs to your laptop and run the command in import_command.txt"
echo "  8. Compile: ./compile evidence/ --claim-type gpu_attested_identity_window -v"
